In [4]:
import subprocess
import numpy as np
x0 = 10.0
x1 = 10.0
x2 = 10.0
epsilon = 0.0001
x_init = np.array([x0,x1,x2])
for ep0 in np.arange(0,0.1,0.01):
    for ep1 in np.arange(0,0.1,0.01):
        for ep2 in np.arange(0,0.1,0.01):
            x = x_init + np.array([ep0,ep1,ep2])
            data = subprocess.run(["./getGradient.exe", "19598,[%f,%f,%f]" %(x[0],x[1],x[2])],stdout=subprocess.PIPE).stdout.decode("utf-8")
            data = data.replace('\r\n',',')
            data = data.replace('[','')
            data = data.replace(']','')
            data = np.fromstring(data, dtype = np.float64,sep =',')
            f_x_old = data[0]
            grad_x = data[1:]
            iteration = 1
            print(x,end=" ")
            while True:
                x = x - grad_x/(1+iteration)
                data = subprocess.run(["./getGradient.exe", "19598,[%f,%f,%f]" %(x[0],x[1],x[2])],stdout=subprocess.PIPE).stdout.decode("utf-8")
                data = data.replace('\r\n',',')
                data = data.replace('[','')
                data = data.replace(']','')
                data = np.fromstring(data, dtype = np.float64,sep =',')
                f_x_new = data[0]
                grad_x = data[1:]
                if abs(f_x_new - f_x_old)<epsilon:
                    break
                else:
                    f_x_old = f_x_new
                    iteration = iteration + 1
            print(x,iteration)


[10. 10. 10.] [0.55 0.71 0.29] 2
[10.   10.   10.01] [0.55 0.71 0.29] 2
[10.   10.   10.02] [0.55 0.71 0.29] 2
[10.   10.   10.03] [0.55 0.71 0.29] 2
[10.   10.   10.04] [0.55 0.71 0.29] 2
[10.   10.   10.05] [0.55 0.71 0.29] 2
[10.   10.   10.06] [0.55 0.71 0.29] 2
[10.   10.   10.07] [0.55 0.71 0.29] 2
[10.   10.   10.08] [0.55 0.71 0.29] 2
[10.   10.   10.09] [0.55 0.71 0.29] 2
[10.   10.01 10.  ] [0.55 0.71 0.29] 2
[10.   10.01 10.01] [0.55 0.71 0.29] 2
[10.   10.01 10.02] [0.55 0.71 0.29] 2
[10.   10.01 10.03] [0.55 0.71 0.29] 2
[10.   10.01 10.04] [0.55 0.71 0.29] 2
[10.   10.01 10.05] [0.55 0.71 0.29] 2
[10.   10.01 10.06] [0.55 0.71 0.29] 2
[10.   10.01 10.07] [0.55 0.71 0.29] 2
[10.   10.01 10.08] [0.55 0.71 0.29] 2
[10.   10.01 10.09] [0.55 0.71 0.29] 2
[10.   10.02 10.  ] [0.55 0.71 0.29] 2
[10.   10.02 10.01] [0.55 0.71 0.29] 2
[10.   10.02 10.02] [0.55 0.71 0.29] 2
[10.   10.02 10.03] [0.55 0.71 0.29] 2
[10.   10.02 10.04] [0.55 0.71 0.29] 2
[10.   10.02 10.05] [0.55 0.71 

In [6]:
while True:
    output = subprocess.run(["./getGradient.exe", "19598,[%f,%f,%f]" %(x[0],x[1],x[2])],stdout=subprocess.PIPE).stdout.decode("utf-8").strip()
    print(output)
    data = output.replace('[','')
    data = data.replace(']','')
    data = np.fromstring(data, dtype = float,sep =',')
    f_x_new = data[0]
    grad_fx = data[1:]
    x = np.subtract(x,np.multiply(grad_fx,1/(k+1)))
    #print(np.linalg.norm(grad_fx)*(1/k+1))
    print(f_x_new,f_x_old,x,grad_fx,k)
    if (np.linalg.norm(grad_fx)**2)*(1/(k+1)) < epsilon:
        break
    else:
        f_x_old = f_x_new
    k = k+1

269.89,[18.90,18.58,19.42]


NameError: name 'k' is not defined